<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Helpers\OCPP21_edition2_part2_specification.pdf" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Helpers\OCPP21_edition2_part2_specification.pdf" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Core" Version="1.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.WebSockets" Version="2.3.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AlfaCharge.Domain\AlfaCharge.Domain.csproj" />
    <ProjectReference Include="..\AlfaCharge.Infrastructure\AlfaCharge.Infrastructure.csproj" />
  </ItemGroup>

</Project>
